services:

  db-1:
    image: rust_backendd_2:latest

    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/health/check" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s

  db-5:
    image: nginx:latest

    ports:
      - "8084:8080"
    depends_on:
      db-1:
        condition: service_healthy

  db-2:
    build: .

    ports:
      - "8081:8080"
    depends_on:
      - db-5

  db-6:
    image: nginx:latest
    ports:
      - "8085:8080"
    depends_on:
      - db-2

  db-4:
    image: rust_backendd_2:latest

    ports:
      - "8083:8080"
    depends_on:
      - db-6
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/health/check" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s

  db-3:
    image: nginx:latest
    ports:
      - "8082:8080"
    depends_on:
      db-4:
        condition: service_healthy

  db-7:
    build:
      context:  https://github.com/Rohaan-Taneja/rust_dockeCompose_cli_app.git

    ports:
      - "8086:8080"
